#!/usr/bin/env bash

source "$HOME/.config/sketchybar/variables.sh" # Loads all defined colors

# General bar and defaults

sketchybar --bar height=30 \
  color="$BAR_COLOR" \
  shadow="$SHADOW" \
  position=top \
  sticky=on \
  padding_right=10 \
  padding_left=10 \
  corner_radius="$CORNER_RADIUS" \
  y_offset=2 \
  margin=10 \
  blur_radius=20 \
  notch_width=200 \
  --default updates=when_shown \
  icon.font="$FONT:Bold:16" \
  icon.color="$ICON_COLOR" \
  icon.padding_left="$PADDINGS" \
  icon.padding_right="$PADDINGS" \
  label.font="$FONT:Bold:16.0" \
  label.color="$LABEL_COLOR" \
  label.padding_left="$PADDINGS" \
  label.padding_right="$PADDINGS" \
  background.padding_right="$PADDINGS" \
  background.padding_left="$PADDINGS" \
  popup.background.border_width=1 \
  popup.background.corner_radius=12 \
  popup.background.border_color="$POPUP_BORDER_COLOR" \
  popup.background.color="$POPUP_BACKGROUND_COLOR" \
  popup.background.shadow.drawing="$SHADOW"

# Left
source "$HOME/.config/sketchybar/plugins/apple.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/calendar_item.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/timer.sh"

#################### Finalizing Setup ####################

sketchybar --hotload true

sketchybar --update

# Launch Dynamic island with sketchybar
dynamic-island

echo "sketchybar configuration loaded.."
